### PR TITLE
Added Frontend Websocket Connection

### PR DESCRIPTION
**Pull request by Dylan-Wheeler**

### CODE REVIEW

**Review by PriyavartRajain — COMMENTED** [review]
Everything looks good but after sending one image to the server, the connection dies.

**Comment by kaitlin31415** [comment]
@PriyavartRajain is this a python Error? Does the server shut off?

**Comment by PriyavartRajain** [comment]
It does appear to be a python error: 

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/websockets/legacy/server.py", line 231, in handler       
    await self.ws_handler(self)
  File "/c/Users/rajai/Documents/BCI_Test/BCI4KidsMediapipe/Python-Websocket-Test/basicEchoWebsocket.py", line 7, in echo
    async for message in websocket:
  File "/usr/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 481, in __aiter__   
    yield await self.recv()
  File "/usr/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 552, in recv        
    await self.ensure_open()
  File "/usr/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 929, in ensure_open 
    raise self.connection_closed_exc()websockets.exceptions.ConnectionClosedError: sent 1009 (message too big); no close frame received

**Comment by kaitlin31415** [comment]
Okay there are a couple of things that I'm thinking of in my head. One is that the message received from to the backend is too large and isn't actually getting processed. i.e. no full frame is being received. Or when it goes to send it back its too big and crashes. Best way to check is to include a print statement before the await statement to see if this is the case or not. We may have to send the image in multiple messages from the frontend and look for something on the backend. 

@Noah-Giustini Please be aware of this as your trying out your code. 

This comment may be helpful for debugging. I am expecting the frame is too large to send over one message. 

https://github.com/aaugustin/websockets/issues/368#issuecomment-386910975

**Comment by kaitlin31415** [comment]
I saw the same issue as @PriyavartRajain - we tested with @Noah-Giustini 's code so we know the image is coming through appropriately. I get the same issue where the payload is too big:
```
python image_intake.py
connection handler failed
Traceback (most recent call last):
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 944, in transfer_data
    message = await self.read_message()
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 1068, in read_message
    frame = await self.read_data_frame(max_size=max_size)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 1089, in read_data_frame
    frame = await self.read_frame(max_size)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 1148, in read_frame
    extensions=self.extensions,
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\framing.py", line 95, in read
    raise PayloadTooBig(f"over size limit ({length} > {max_size} bytes)")      
websockets.exceptions.PayloadTooBig: over size limit (90423 > 1093 bytes)      

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\server.py", line 231, in handler
    await self.ws_handler(self)
  File "image_intake.py", line 23, in recv_img
    async for message in websocket:
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 481, in __aiter__
    yield await self.recv()
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 552, in recv
    await self.ensure_open()
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 929, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1009 (message too big); no close frame received
connection handler failed
Traceback (most recent call last):
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 541, in run_forever
    self._run_once()
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\server.py", line 231, in handler
    await self.ws_handler(self)
  File "image_intake.py", line 23, in recv_img
    async for message in websocket:
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 481, in __aiter__
    yield await self.recv()
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\legacy\protocol.py", line 538, in recv
    **loop_if_py_lt_38(self.loop),
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 389, in wait
    return await _wait(fs, timeout, return_when, loop)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\tasks.py", line 482, in _wait
    await waiter
concurrent.futures._base.CancelledError
Traceback (most recent call last):
  File "image_intake.py", line 43, in <module>
    asyncio.run(main())
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 574, in run_until_complete
    self.run_forever()
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 541, in run_forever
    self._run_once()
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Kaitlin\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt

```

**Comment by RoxanneDuchesne** [comment]
bug

Same error, payload too big.

**Comment by kaitlin31415** [comment]
The go forward is to merge this into master and then to open a bug so we address the excess payload sizes

**Comment by RoxanneDuchesne** [comment]
Regarding the payload too big error it seems to correlate with FPS.

I'm not 100% on the mechanism behind why the darker it is in your room the lower your framerate is, but it is known that the darker a room is the lower your fps will be. (Something about it taking longer to get enough light exposure to get a picture not really sure tho) 

When I sit in the dark, I can get like 10 frames before the error, but when I sit in the light it errors out right away. Thus, thinking it has to do with framerate.

**Review by PriyavartRajain — APPROVED** [review]

**Pull request merged**
